# PostgreSQL(Supabase) 데이터베이스 연결 및 JPA 설정

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  hikari:
    maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: dev