spring:
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:empty}
        chat:
          options:
            model: gemini-3.5-flash-lite
        embedding:
          api-key: ${GEMINI_API_KEY:empty}
---
spring:
  config:
    activate:
      on-profile: dev