spring:
  application:
    name: MatchEAT
  profiles:
    include: db, ai, account
---
spring:
  config:
    import: optional:file:.env[.properties]
  security:
    user:
      name: user
      password: password
