package org.example.matcheat.domain.account.service;

public enum AccountErrorCode {
    INVALID_EMAIL,
    VALIDATION_FAILED,
    PASSWORD_CONFIRM_MISMATCH,
    EMAIL_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    FORBIDDEN,
    ACCOUNT_SUSPENDED,
    ACCOUNT_WITHDRAWN,
    USER_NOT_FOUND,
    CURRENT_PASSWORD_MISMATCH,
    SELLER_APPLICATION_ALREADY_EXISTS
}
